JobPlatform/Web/JobPlatform.Web/Areas/Employer/Controllers/CandidatesController.cs
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using JobPlatform.Data.Models;
using JobPlatform.Web.ViewModels.Jobs;
using Microsoft.AspNetCore.Identity;

namespace JobPlatform.Web.Areas.Employer.Controllers
{
    using JobPlatform.Common;
    using JobPlatform.Services.Data.Interfaces;
    using JobPlatform.Web.Controllers;
    using JobPlatform.Web.ViewModels.Candidates;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.Employer)]
    [Area("Employer")]
    public class CandidatesController : BaseController
    {
        private readonly ICandidateService candidateService;
        private readonly ICompanyService companyService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IJobService jobService;

        public CandidatesController(
            ICandidateService candidateService,
            ICompanyService companyService,
            UserManager<ApplicationUser> userManager,
            IJobService jobService)
        {
            this.candidateService = candidateService;
            this.companyService = companyService;
            this.userManager = userManager;
            this.jobService = jobService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var companyId = this.companyService.CompanyByUserId(user.Id.ToString());
            if (companyId == null)
            {
                return this.View();
            }

            var viewModel = this.jobService
                    .GetAllJobsByCompanyId<MyCandidatesViewModel>(companyId.Id);

            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            var viewModel = this.candidateService.GetCandidateByUserId<CandidateDetailsViewModel>(id);

            return this.View(viewModel);
        }
    }
}

JobPlatform/Web/JobPlatform.Web/Areas/Employer/Controllers/CompanyController.cs
namespace JobPlatform.Web.Areas.Employer.Controllers
{
    using System.Threading.Tasks;

    using JobPlatform.Common;
    using JobPlatform.Data.Models;
    using JobPlatform.Services.Data.Interfaces;
    using JobPlatform.Web.Controllers;
    using JobPlatform.Web.ViewModels.Companies;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.Employer)]
    [Area("Employer")]
    public class CompanyController : BaseController
    {
            private readonly IFileService fileService;
            private readonly ICompanyService companyService;
            private readonly UserManager<ApplicationUser> userManager;

            public CompanyController(
                IFileService fileService,
                ICompanyService companyService,
                UserManager<ApplicationUser> userManager)
            {
                this.fileService = fileService;
                this.companyService = companyService;
                this.userManager = userManager;
            }

            public async Task<IActionResult> Index()
            {
            var user = await this.userManager.GetUserAsync(this.User);

            var viewModel = this.companyService.CompanyByUserId<CompanySimpleViewModel>(user.Id);

            return this.View(viewModel);
            }

            public IActionResult Details(string id)
            {
                var viewModel = this.companyService.CompanyById<CompanyDetailsViewModel>(id);

                return this.View(viewModel);
            }

            public IActionResult CreateCompany()
            {
                return this.View();
            }

            [HttpPost]
            public async Task<IActionResult> CreateCompany(CompanyCreateViewModel input)
            {
                var user = await this.userManager.GetUserAsync(this.User);

                if (!this.ModelState.IsValid)
                {
                    return this.View(input);
                }

                var img = await this.fileService.UploadImageFileAsync(input.PictureFile, user.Id, "CompanyLogo");

                int result = this.companyService.AddCompany(
                    input.CompanyName,
                    input.SanitizedCompanyDescription,
                    input?.CompanyWebsite,
                    input?.FacebookWebsite,
                    input?.TwitterWebsite,
                    input?.LinkedInWebsite,
                    img?.SecureUri.ToString(),
                    user.Id).Result;

                if (result < 0)
                {
                    return this.View(input);
                }

                return this.RedirectToAction("Index");
            }

            public IActionResult Delete(string id)
            {
                var viewModel = this.companyService.CompanyById<CompanySimpleViewModel>(id);

                return this.View(viewModel);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteCompany(string id)
            {
                var result = this.companyService.DeleteById(id).Result;

                if (!result)
                {
                    return this.NotFound();
                }

                return this.RedirectToAction("Index");
            }

            public IActionResult EditCompany(string id)
            {
                var viewModel = this.companyService.CompanyById<CompanyEditViewModel>(id);

                return this.View(viewModel);
            }

            [HttpPost]
            public async Task<IActionResult> EditCompany(CompanyEditViewModel input)
            {
                var user = await this.userManager.GetUserAsync(this.User);
                if (!this.ModelState.IsValid)
                {
                    return this.View(input);
                }

                var img = await this.fileService.UploadImageFileAsync(input.PictureFile, user.Id, "CompanyLogo");

                int result = this.companyService.EditCompany(
                    input.CompanyName,
                    input.SanitizedCompanyDescription,
                    input?.CompanyWebsite,
                    input?.FacebookWebsite,
                    input?.TwitterWebsite,
                    input?.LinkedInWebsite,
                    img?.SecureUri?.ToString(),
                    input.Id).Result;

                return this.RedirectToAction("Index");
            }
        }
}

JobPlatform/Web/JobPlatform.Web/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Http;

namespace JobPlatform.Web.Controllers
{
    using System.Threading.Tasks;
    using JobPlatform.Data.Models;
    using JobPlatform.Services.Data.Interfaces;
    using JobPlatform.Web.ViewModels.Companies;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = "Administrator, Moderator")]
    public class CompaniesController : BaseController
    {
        private readonly IFileService fileService;
        private readonly ICompanyService companyService;
        private readonly UserManager<ApplicationUser> userManager;

        public CompaniesController(
            IFileService fileService,
            ICompanyService companyService,
            UserManager<ApplicationUser> userManager)
        {
            this.fileService = fileService;
            this.companyService = companyService;
            this.userManager = userManager;
        }

        public IActionResult UploadFile(IFormFile pictureFile)
        {
            return this.Ok();
        }

        public IActionResult Index()
        {
            var viewModel = this.companyService.GetAllCompanies<CompanySimpleViewModel>();

            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            var viewModel = this.companyService.CompanyById<CompanyDetailsViewModel>(id);

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult Company(string id)
        {
            var viewModel = this.companyService.CompanyById<CompanyViewModel>(id);

            return this.View(viewModel);
        }

        public IActionResult Delete(string id)
        {
            var viewModel = this.companyService.CompanyById<CompanySimpleViewModel>(id);

            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult DeleteCompany(string id)
        {
            var result = this.companyService.DeleteById(id).Result;

            if (!result)
            {
                return this.NotFound();
            }

            return this.RedirectToAction("Index");
        }

        public IActionResult EditCompany(string id)
        {
            var viewModel = this.companyService.CompanyById<CompanyEditViewModel>(id);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditCompany(CompanyEditViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            int result = this.companyService.EditCompany(
                input.CompanyName,
                input.SanitizedCompanyDescription,
                input?.CompanyWebsite,
                input?.FacebookWebsite,
                input?.TwitterWebsite,
                input?.LinkedInWebsite,
                null,
                input.Id).Result;

            return this.RedirectToAction("Details");
        }
    }
}

JobPlatform/Web/JobPlatform.Web/Controllers/JobsController.cs
namespace JobPlatform.Web.Controllers
{
    using System.Threading.Tasks;

    using JobPlatform.Common;
    using JobPlatform.Data.Models;
    using JobPlatform.Services.Data.Interfaces;
    using JobPlatform.Web.ViewModels.Companies;
    using JobPlatform.Web.ViewModels.Jobs;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = "Administrator, Moderator")]
    public class JobsController : BaseController
    {
        private readonly IJobService jobService;
        private readonly ICompanyService companyService;
        private readonly UserManager<ApplicationUser> userManager;

        public JobsController(
            IJobService jobService,
            ICompanyService companyService,
            UserManager<ApplicationUser> userManager)
        {
            this.jobService = jobService;
            this.companyService = companyService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var viewModel = this.jobService.GetAllJobs<JobSimpleViewModel>();
            return this.View(viewModel);
        }

        public IActionResult DeleteJob(string id)
        {
            var viewModel = this.jobService.GetJobById<DeletedJobViewModel>(id);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteJobConfirm(string id)
        {
            await this.jobService.DeleteJobById(id);
            return this.RedirectToAction("Index");
        }

        public IActionResult EditJob(string id)
        {
            var viewModel = this.jobService.GetJobById<EditJobViewModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditJob(EditJobViewModel input)
        {
            await this.jobService.EditJob(
                input.Id,
                input.CompanyEmail,
                input.JobTitle,
                input.JobCategory,
                input.LocationCity,
                input.JobType,
                input.Description);

            return this.RedirectToAction("Index");
        }

        public IActionResult Details(string id)
        {
            var viewModel = this.jobService.GetJobById<JobDetailsViewModel>(id);

            return this.View(viewModel);
        }
    }
}

JobPlatform/Web/JobPlatform.Web/Views/Shared/_Layout.cshtml
@using JobPlatform.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/jquery.dataTables.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar col-12 navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container col-10">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item align-baseline">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_NavigationPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container col-12">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea",
            plugins: [
                "image paste table link code media"
            ]
        });
    </script>
<environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script type="text/javascript" charset="utf8" src="~/js/jquery.dataTables.js"></script>
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script type="text/javascript" charset="utf8" src="~/js/jquery.dataTables.js"></script>
    </environment>
    @this.RenderSection("Scripts", required: false)
</body>
</html>

JobPlatform/Web/JobPlatform.Web/Views/Shared/_NavigationPartial.cshtml
@using JobPlatform.Common
@using JobPlatform.Data.Models
@using Microsoft.AspNetCore.Identity


@if (this.User.IsInRole(@GlobalConstants.Moderator) || this.User.IsInRole(@GlobalConstants.Administrator))
{
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Companies
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-dark"  asp-controller="Companies" asp-action="Index">All Companies</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Jobs
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-dark"  asp-controller="Jobs" asp-action="Index">Jobs</a>
        </div>
    </li>
}
else if (this.User.IsInRole(@GlobalConstants.Employer))
{
    <li class="nav-item align-baseline">
        <a class="nav-link text-dark" asp-area="Employer" asp-controller="Company" asp-action="Index">Company</a>
    </li>
    <li class="nav-item align-baseline">
        <a class="nav-link text-dark" asp-area="Employer" asp-controller="Jobs" asp-action="Index">Jobs</a>
    </li>
    <li class="nav-item align-baseline">
        <a class="nav-link text-dark" asp-area="Employer" asp-controller="Candidates" asp-action="Index">Candidates</a>
    </li>
}
else if (this.User.IsInRole(@GlobalConstants.UserRole))
{
    <li class="nav-item align-baseline">
        <a class="nav-link text-dark" asp-area="User" asp-controller="Companies" asp-action="Index">Companies</a>
    </li>
    <li class="nav-item align-baseline">
        <a class="nav-link text-dark" asp-area="User" asp-controller="Jobs" asp-action="Index">Jobs</a>
    </li>
    <li class="nav-item align-baseline">
        <a class="nav-link text-dark" asp-area="User" asp-controller="Jobs" asp-action="MyApplications">My Applications</a>
    </li>
}