JobPlatform/Web/JobPlatform.Web/Areas/Administration/Controllers/DashboardController.cs
using JobPlatform.Services.Data.Interfaces;

namespace JobPlatform.Web.Areas.Administration.Controllers
{

    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        private readonly IUserService userService;

        public DashboardController(IUserService userService)
        {
            this.userService = userService;
        }

        public IActionResult Dashboard()
        {
            return this.View();
        }

        public IActionResult Settings()
        {
            return this.View();
        }
    }
}

JobPlatform/Web/JobPlatform.Web/Areas/Administration/Controllers/UsersController.cs
namespace JobPlatform.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using JobPlatform.Services.Data.Interfaces;
    using JobPlatform.Web.ViewModels.Administration.Dashboard;
    using JobPlatform.Web.ViewModels.Administration.Dashboard.Users;
    using Microsoft.AspNetCore.Mvc;

    public class UsersController : AdministrationController
    {
        private readonly IUserService userService;

        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> Users()
        {
            var viewModel = new UsersViewModel
            {
                Users = await this.userService.GetAllUsersAsync(),
                Roles = this.userService.GetAllRoles<RoleViewModel>(),
            };

            if (viewModel.Users == null && viewModel.Roles == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult UserById(string id)
        {
            var viewModel = this.userService
                .GetAllUsers<SelectedUserViewModel>()
                .FirstOrDefault(x => x.Id == id);
            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

    }
}

JobPlatform/Web/JobPlatform.Web/Controllers/SettingsController.cs
using JobPlatform.Services.Data.Interfaces;

namespace JobPlatform.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using JobPlatform.Data.Common.Repositories;
    using JobPlatform.Data.Models;
    using JobPlatform.Services.Data;
    using JobPlatform.Web.ViewModels.Settings;

    using Microsoft.AspNetCore.Mvc;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = this.settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return this.View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await this.repository.AddAsync(setting);
            await this.repository.SaveChangesAsync();

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

JobPlatform/Web/JobPlatform.Web/Areas/Administration/Views/Dashboard/Dashboard.cshtml
@model JobPlatform.Web.ViewModels.Administration.Dashboard.Users.UsersViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>

<form id="userForm" method="post"></form>
<table class="table">

        <tr>
            <td>
            <a class="nav-link text-dark" asp-area="Administration" asp-controller="Users" asp-action="Users">Users</a>
            </td>
        </tr>
</table>

JobPlatform/Web/JobPlatform.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model JobPlatform.Web.ViewModels.Administration.Dashboard.UsersViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>

<form id="userForm" method="post"></form>
<table class="table">

        <tr>
            <td>
            <a class="nav-link text-dark" asp-area="Administration" asp-controller="Users" asp-action="Users">Users</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </td>
        </tr>
</table>